opencost:
  prometheus:
    install: false
    
  opencost:
    prometheus:
      external:
        enabled: true    
        url: "http://prometheus-server.prometheus.svc.cluster.local:80"
      internal:
        enabled: false
