apiVersion: v2
name: grafana-wrapper
description: Wrapper per l'installazione di Grafana
type: application
version: 1.0.0
appVersion: "10.5.8"

dependencies:
  - name: grafana
    version: 10.5.8
    repository: https://grafana.github.io/helm-charts
